global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: eureka-server
  metrics_path: /actuator/prometheus
  scrape_interval: 10s
  static_configs:
    - targets: ['172.21.0.2:8761']
      labels:
        group: 'production' 
- job_name: uniselos-api
  metrics_path: /uniselos-api/metrics
  scrape_interval: 10s
  static_configs:
    - targets: ['docker.test.ceuma.edu.br:3075']
      labels:
        group: 'production' 